version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api:
    build:
      context: .
      dockerfile: Dockerfile.pip
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    volumes:
      - ./app:/src/app
      - ./logging_service:/src/logging_service
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
      PROJECT_NAME: "Agent-Scheduling"
      LEAD_AGENT_CONFIG_PATH: /src/app/server_config.lead_agent.json
    # volumes:
    #   - ./custom_config:/src/custom_config  # Mount custom config directory if using custom path

  worker:
    build:
      context: .
      dockerfile: Dockerfile.pip
    command: celery -A app.tasks worker --concurrency=4 --loglevel=info
    depends_on:
      - rabbitmq
    volumes:
      - ./app:/src/app
      - ./logging_service:/src/logging_service
    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}
      PROJECT_NAME: "Agent-Scheduling"
      LEAD_AGENT_CONFIG_PATH: /src/app/server_config.lead_agent.json
