version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management # RabbitMQ with management UI
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ broker port
      - "15672:15672" # Management console port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  db:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
      - rabbitmq
      - db
    ports:
      - "8000:8000"
    volumes:
      # Mount only the app source code, preserving the virtual environment
      - ./api:/src/api
      - ./database:/src/database
      - ./mq:/src/mq
      # Mount pyproject.toml and uv.lock for dependency changes
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      DATABASE_NAME: mydatabase
