FROM python:3.12-slim-bookworm

WORKDIR /src

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app ./app
COPY ./logging_service ./logging_service
COPY ./servers ./servers

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
