version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management # RabbitMQ with management UI
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ broker port
      - "15672:15672" # Management console port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
