[project]
name = "agent-orchestration"
version = "0.1.0"
description = "Tinkering with Agent Orchestration"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pika>=1.3.2",
    "python-dotenv>=1.1.1",
]
